spring:
  application:
    name: evm-transaction-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/EVM_TRANSACTION_SERVICE}
    username: ${DB_USER:testUser}
    password: ${DB_PASSWORD:testPassword}
  flyway:
    enabled: true
    schemas: flyway_schema
    locations: classpath:db/migration
  jpa:
    open-in-view: false
evm:
  node-url: ${EVM_NODE_URL}
  api-key: ${EVM_API_KEY}